server:
  port: 8081

spring:
  application:
    name: CapitalHub
  datasource:
    # Conectamos a localhost porque corremos el Java en local, no en Docker
    url: jdbc:mysql://localhost:3306/capitalhub?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update # Usar 'update' para el MVP es más seguro si Flyway falla
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true # Importante si la DB ya tiene cosas

jwt:
  secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970" # Clave base64 válida
  expiration: 86400000 # 1 día

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: capitalhub-media