version: '3.8'

services:
  # 1. BASE DE DATOS (MySQL)
  capitalhub-mysql:
    image: mysql:8.0
    container_name: capitalhub-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin  # Contraseña root
      MYSQL_DATABASE: capitalhub  # Nombre de la DB que creará automáticamente
      MYSQL_PASSWORD: admin       # Contraseña usuario
    ports:
      - "3306:3306"               # IMPORTANTE: Expone el puerto 3306 a tu máquina local
    volumes:
      - mysql_data:/var/lib/mysql # Persistencia de datos

  # 2. ALMACENAMIENTO (MinIO - Similar a S3)
  capitalhub-minio:
    image: minio/minio
    container_name: capitalhub-minio
    restart: always
    ports:
      - "9000:9000" # Puerto API
      - "9001:9001" # Puerto Consola Web
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

# Volúmenes para que los datos no se borren al reiniciar
volumes:
  mysql_data:
  minio_data: